[application]

[web.app]

# HTML title tag content
title = "dioxus-notebook"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

script = [
     "/assets/echarts/echarts.min.js",
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
